# Configuration file for multi-device setup example
[device.ob_lidar1]
name = "ob_lidar1"
model = "TL2401"

[device.ob_lidar1.network]
single_port_mode = true
ip = "192.168.1.100"
protocol = "udp"
port = 2401
# if single_port_mode is true, the following ports are ignored
command_port = 2368
point_cloud_port = 2369
imu_port = 2370
log_port = 2371

[device.ob_lidar2]
name = "ob_lidar2"
model = "TL2401"

[device.ob_lidar2.network]
single_port_mode = true
ip = "192.168.1.101"
port = 2401
# if single_port_mode is true, the following ports are ignored
protocol = "tcp"
command_port = 2372
point_cloud_port = 2373
imu_port = 2374
log_port = 2375

[logging]
max_file_size = 10485760 # 10M
max_file_num = 10
log_file_dir = "/tmp"
console_log_level = "info"
file_log_level = "info"
log_to_console = true
log_to_file = true
