# Configuration file for single device setup example
[device.ob_lidar]
name = "ob_lidar"
model = "MS600"

[device.ob_lidar.network]
single_port_mode = true
ip = "192.168.1.100"
protocol = "udp"
port = 2228

[logging]
max_file_size = 10485760 # 10M
max_file_num = 10 # max file number is 10
log_file_dir = "/tmp"
console_log_level = "info"
file_log_level = "info"
log_to_console = true
log_to_file = true
